### ISSUE TITLE
json fail to build with GHC-8.4.1

### ISSUE THREAD

**Issue by phadej** [GaloisInc/json#6]
```
Text/JSON/Pretty.hs:55:32: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Text/JSON/Pretty.hs:13:8-23
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.HughesPJ.<>’,
                             imported from ‘Text.PrettyPrint.HughesPJ’ at Text/JSON/Pretty.hs:19:1-32
   |
55 |         uni_esc c = text "\\u" <> text (pad 4 (showHex (fromEnum c) ""))
   |                                ^^
```

I'll make a revision on Hackage adding `base <4.11` bound after GHC-8.4.1 proper is released.

cc @hvr

**Comment by yav** [comment]
Hi,
I don't have GHC 8.4 to test with, and this seems like a rather unfortunate name clash, but for now I pushed a patch that qualifies the uses of <>.  Could you try it out and let me know if that fixes the problem?

**Comment by phadej** [comment]
It seems to work, thanks!

BTW, could you enable Travis for this repository: https://travis-ci.org/GaloisInc/json, @hvr kindly makes packages also for GHC-8.0.2, GHC-8.2.2 and GHC-8.4.1 (which aren't in your config, but that's simple addition!)

**Comment by yav** [comment]
OK, should be turned on now.
